### ISSUE TITLE
Sub-transaction for trade_update.sql Frame 3

### ISSUE THREAD

**Issue by MaheshGouru** [osdldbt/dbt5#5] opened 2022-07-26 16:04 UTC
[storedproc/pgsql/pgsql/trade_update.sql](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_update.sql)

The sub-transaction control should be added as the start transaction and the commit transaction are identified in the TPC-Ev1.14 Pseudo-code (Page 176 of 287).

Starting the sub-transaction would be on [line 391](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_update.sql#L391)

The preliminary conversion to a stored procedure would be implemented by adhering to convention and adding COMMIT after the "END LOOP;" on [line 572](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_update.sql#L572). 

There are no explicit ROLLBACK calls in either the 3.3.10.2 Trade-Update Transaction Database Footprint or the Trade-Update_Frame-3 Pseudo-code to implement.

Updating the CREATE FUNCTION with CREATE PROCEDURE on [line 363](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_update.sql#L363)

The parameter changes to handle the return values would be on [line 521](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_update.sql#L521) and [line 571](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_update.sql#L571).

---
Modification to the C++ code to call the procedure would be on [line 249](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/src/transactions/TradeUpdateDB.cpp#L249)

**Comment by markwkm** [comment] 2022-07-27 00:09
Duplicate of #2.

> The sub-transaction control should be added as the start transaction and the commit transaction are identified in the TPC-Ev1.14 Pseudo-code (Page 176 of 287).

That's actually not correct, there's no need for subtransactions here.  This is covered by the top level transaction control statements in the C++ code.

**Closed by markwkm** 2022-07-27 00:09 UTC
